# cython: language_level=3
# cython: nonecheck=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: infer_types=True
# cython: wraparound=False
# cython: boundscheck=False

"""
Auto-generated consolidated vector_implementations module.
This file is automatically generated by setup.py and includes all individual
vector implementation files in the vectors directory.

DO NOT EDIT THIS FILE MANUALLY - it will be overwritten during build.
"""

# Only define NULL_HASH once to avoid redeclaration
from libc.stdint cimport uint64_t
cdef uint64_t NULL_HASH = <uint64_t>0x9e3779b97f4a7c15

include "bool_vector.pyx"
include "int64_vector.pyx"
include "float64_vector.pyx"
include "array_vector.pyx"
include "date32_vector.pyx"
include "string_vector.pyx"
include "time_vector.pyx"
include "timestamp_vector.pyx"
