name: Static Analysis

on:
  - workflow_call
  - push

jobs:
  test:
    name: Bandit Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set Up Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade bandit

      - name: Execute Test
        run: bandit -c pyproject.toml -r draken

  mypy:
    name: Type Checks
    runs-on: ubuntu-latest
    if: false  # disable the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set Up Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip uv mypy
          python -m uv pip install --upgrade -r pyproject.toml
          python -m uv pip install --upgrade -r pyproject.toml --extra=dev

      - name: Execute Test
        run: mypy --ignore-missing-imports --python-version 3.11 --no-strict-optional --check-untyped-defs draken
